//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public string Accion { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<int> TipoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> SolicitudId { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> AccionId { get; set; }
        public string Tecnico { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public string EnvioEmail { get; set; }
    
        public virtual AccionLog AccionLog { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Solicitud Solicitud { get; set; }
        public virtual TipoLog TipoLog { get; set; }
    }
}
