//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRol
    {
        public int PersonalRol1 { get; set; }
        public int RolId { get; set; }
        public int PersonalId { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
