//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenSolicitudesMobile
    {
        public int SolicitudId { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_resolucion { get; set; }
        public Nullable<System.DateTime> fecha_comprometida { get; set; }
        public string Descr { get; set; }
        public string SolicitanteEmail { get; set; }
        public string SolicitanteIdRed { get; set; }
        public string Obra_Oficina_SVenta { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> EstadoSolicitudId { get; set; }
        public string Empresa { get; set; }
        public string Tipo_Solicitud { get; set; }
        public string resposable { get; set; }
        public string estado { get; set; }
        public string Telefono { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> Fecha_Status { get; set; }
        public string UserIdRed { get; set; }
        public string Descr_Status { get; set; }
        public string Obra { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public string Nombre { get; set; }
        public string NombreCompleto { get; set; }
        public string Apellidopaterno { get; set; }
        public string nickname { get; set; }
    }
}
