//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sociedades
    {
        public int Id { get; set; }
        public string Rut { get; set; }
        public string Descripcion { get; set; }
        public string Regional { get; set; }
        public Nullable<int> RegionalId { get; set; }
    }
}
