//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.DocAdjuntos = new HashSet<DocAdjuntos>();
            this.Log = new HashSet<Log>();
            this.Status = new HashSet<Status>();
            this.TareaSolicitud = new HashSet<TareaSolicitud>();
        }
    
        public int SolicitudId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_resolucion { get; set; }
        public Nullable<System.DateTime> fecha_comprometida { get; set; }
        public Nullable<int> EstadoSolicitudId { get; set; }
        public string Descr { get; set; }
        public string SolicitanteEmail { get; set; }
        public Nullable<int> TipoSolicitudId { get; set; }
        public string SolicitanteIdRed { get; set; }
        public string Obra_Oficina_SVenta { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public string Telefono { get; set; }
        public string Obra { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public Nullable<int> CategoriaSolicitudId { get; set; }
        public Nullable<int> EsIncidente { get; set; }
        public Nullable<int> SubCategoriaId { get; set; }
        public Nullable<int> Area { get; set; }
        public string SolicitanteNombre { get; set; }
        public string Sociedad { get; set; }
        public string Creacion { get; set; }
        public string CCyP { get; set; }
        public Nullable<int> SolicitanteId { get; set; }
        public Nullable<int> Referencia { get; set; }
    
        public virtual Area Area1 { get; set; }
        public virtual CategoriaSolicitud CategoriaSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAdjuntos> DocAdjuntos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EstadoSolicitud EstadoSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Solicitante Solicitante { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareaSolicitud> TareaSolicitud { get; set; }
    }
}
