//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusId { get; set; }
        public int SolicitudId { get; set; }
        public string Descr { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string UserIdRed { get; set; }
        public Nullable<bool> Esmobile { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
