//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudSoporteSistemas_prd
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaSolicitud
    {
        public int TareaSolicitudId { get; set; }
        public Nullable<int> TipoTareaId { get; set; }
        public int SolicitudId { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_comprometida_inicio { get; set; }
        public Nullable<System.DateTime> fecha_comprometida_fin { get; set; }
        public string Descr { get; set; }
        public string ResponsableIdRed { get; set; }
        public string Externo { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual TipoTarea TipoTarea { get; set; }
    }
}
